package com.myAgeEducation.cbseClass6New.maths.perimeterarea;

public enum PerimeterAreaQuestionType {
    CONCEPT,
    PERIMETER_SQUARE,
    PERIMETER_RECTANGLE,
    AREA_COMPARISON,
    PERIMETER_COMPARISON,
    TILE_COVERING,
    GRID_AREA_COMPARISON,
    SAME_AREA_COMPARISON,
    GRID_MULTI_SHAPE_QUIZ,
    AREA_LOGIC_COMPARISON,
    VOLUME_CUBE,
    VOLUME_CUBOID,
    GRID_DESIGN_AREA,
    PERIMETER_FROM_SHAPE,
    MISSING_SIDE_FROM_PERIMETER
}
